# Generated by Django 2.0.9 on 2020-05-29 

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VZBackupRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('readwrite', 'Read Write'), ('usermanagement', 'User Management'), ('downloadbackups', 'Download Backups'), ('readonly', 'Read Only')),
            },
        ),
    ]
